#!/bin/bash -ex

. ./install-debian-console

# Install packages
sudo apt-get install -y \
    fonts-vlgothic ibus-mozc \
    numix-gtk-theme numix-icon-theme \
    vim-gui-common xdotool \
    dia dia-gnome
    keepass2 \
    chromium

# TODO: For Mac Book Pro
# sudo apt-get install -y firmware-amd-graphics xserver-xorg-video-amdgpu
