#!/bin/bash -xe

# Check whether ``sudo`` is installed
# This check MUST be put first of all procedures
which sudo || \
    ( su -c "apt-get install -y sudo && usermod -aG sudo $(whoami)" &&\
    echo "Logout and re-execute ./install" || true && exit 1)


# Script global variables
INSTALLER_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
BASHRC_PART_PATH=$(t=$(mktemp) && chmod 600 $t && echo $t)


# Update
[ 1 -gt $(find /var/cache/apt/pkgcache.bin -mtime -1 | wc -l) ] && sudo apt-get update

. ./install.d/00-helper.bash
. ./install.d/10-repository.bash
. ./install.d/20-packages.bash
. ./install.d/30-python.bash
. ./install.d/90-dotfiles.bash


# REMAIN BREW CODES IN THIS FILE
# The codes run finall steps using varibles declared in this file.

# Generate a part of bashrc
part="${HOME}/.provisioned_bashrc_part"
mv -fv ${BASHRC_PART_PATH} ${part}

# Configure bashrc
echo "source ${part}" | \
    append_marker_leaded_lines '# Load provisioned' ${HOME}/.bashrc
